name: midnightcity
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  #sdk: ^3.5.1
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  adaptive_theme: ^3.1.0
  awesome_notifications: ^0.9.3+1
  banner_carousel: ^1.2.1
  #basic_utils: ^3.9.0
  basic_utils: ^5.7.0
  cached_network_image: ^3.2.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.1
  contained_tab_bar_view: ^0.8.0
  cool_alert: ^2.0.1
  country_picker: ^2.0.15
  currency_formatter: ^2.2.1
  custom_clippers: ^2.0.0
  dartx: ^1.1.0
  #date_time_picker: ^2.0.0
 # dio: ^4.0.6
  dio: ^5.7.0
  #dio_http_cache_lts: ^0.4.0
  dotted_border: ^2.0.0+2
  dotted_line: ^3.1.0
  double_back_to_close: ^2.0.0
  dynamic_height_grid_view: ^0.0.3
  equatable: ^2.0.3
  expand_widget: ^3.1.1
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  firebase_crashlytics: ^4.1.1
  firebase_messaging: ^15.1.1
  flag: ^7.0.0
  flutter_facebook_auth: ^7.1.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_branch_sdk: ^8.2.0
  flutter_firebase_chat_core: ^1.6.8




  # firebase_auth: ^3.4.1
  # firebase_core: ^1.19.1
  # firebase_crashlytics: ^2.8.4
  #firebase_dynamic_links: ^4.3.1-depricated
  #firebase_messaging: ^11.4.4
  # flag: ^5.0.1
  #flutter_facebook_auth: ^4.4.0+1
  #flutter_form_builder: ^7.3.1
  flutter_form_builder: ^9.4.1
  #flutter_icons: ^1.0.0
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_overboard: ^3.1.1
  flutter_rating_bar: ^4.0.1
  flutter_signin_button: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  #flutter_svg: ^1.1.1+1
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  flutter_widget_from_html_core: ^0.15.2
  #fluttercontactpicker: ^4.7.0
  fluttertoast: ^8.0.9
  form_builder_validators: ^11.0.0
  #geolocator: ^9.0.2
  geolocator: ^10.0.1
  glass: ^2.0.0+1
  glass_kit: ^4.0.1
  #google_fonts: ^3.0.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.1.8
  # google_maps_place_picker_mb: ^2.0.0-mb.20
  google_maps_place_picker_mb: ^3.1.2
  google_nav_bar: ^5.0.6
  google_places_flutter: ^2.0.5
  google_sign_in: ^6.2.1
  group_radio_button: ^1.2.0
  #http: ^0.13.4
  http: ^1.2.2
  image_picker: ^1.1.2
  in_app_review: ^2.0.4
  inspection: ^0.0.13
  intl: ^0.19.0
  #jiffy: ^5.0.0
  jiffy: ^6.3.1
  line_icons: ^2.0.1
  localize_and_translate: ^4.1.1
  location: ^6.0.2
  map_launcher: ^3.5.0
  masonry_grid: ^1.0.0
  measure_size: ^4.0.0
 # package_info: ^2.0.2
  package_info_plus: ^4.2.0
  pin_code_fields: ^8.0.1
  pinch_zoom: ^2.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  pull_to_refresh_flutter3: ^2.0.1
  qr_code_scanner: ^1.0.0
  random_string: ^2.3.1
  rx_shared_preferences: ^3.0.0
  share_plus: ^10.0.2
  #share: ^2.0.4
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^6.1.2
  singleton: ^0.0.3-nullsafety
  slide_countdown: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  # spider: ^2.1.0
  spider: ^4.2.2
  stacked: ^3.4.3
  sticky_headers: ^0.3.0+2
  supercharged: ^2.1.1
  # ticketview: ^1.0.0
  timelines: ^0.1.0
  upgrader: ^11.1.0
  url_launcher: ^6.1.4
  velocity_x: ^4.2.1
  what3words: ^3.1.0
  #flutter_termii: ^0.2.1
  #whatsapp: ^1.0.6
  whatsapp: ^3.0.0
  easy_autocomplete: ^1.6.0
  autocomplete_textfield: ^2.0.1
  visibility_detector: ^0.4.0+2
  flutter_launcher_icons: ^0.14.1
  flutter_icons:
    git:
      url: https://github.com/imclerran/flutter-icons.git
      ref: dart-3

dev_dependencies:
  flutter_application_id: ^2.0.0-dev
 # flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.2.4

  flutter_test:
    sdk: flutter
  #translator: ^0.1.7
  translator: ^1.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#flutter_launcher_icons:
 # android: "launcher_icon"
  #ios: true
  #remove_alpha_ios: true
  #image_path: "assets/images/app_icon.png"
 # adaptive_icon_foreground: "assets/images/app_icon.png"
  #adaptive_icon_background: "assets/images/splash_screen.png"
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/json/
    - assets/lang/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
